name: Update Externals

on:
  workflow_dispatch:
    inputs:
      subtree:
        description: 'Select subtree to update'
        required: true
        type: choice
        options:
          - aravis
          - opencv
  workflow_call:
    inputs:
      subtree:
        description: 'Select subtree to update'
        required: true
        type: string

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git state
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone --no-checkout ${{ github.server_url }}/${{ github.repository }}.git .
          git fetch --all --tags

      - name: Update Aravis Subtree
        if: inputs.subtree == 'aravis'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH="external/$(echo ${{ inputs.subtree }} | sed 's/^./\U&/')"
          git checkout -B $BRANCH origin/$BRANCH
          git subtree pull --prefix aravis https://github.com/AravisProject/aravis.git main --squash
          git commit -m "chore: update aravis subtree" || echo "No changes to commit"
          git push https://git:${GH_TOKEN}@github.com/${{ github.repository }}.git $BRANCH

      - name: Update OpenCV Subtree
        if: inputs.subtree == 'opencv'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH="external/$(echo ${{ inputs.subtree }} | sed 's/^./\U&/')"
          git checkout -B $BRANCH origin/$BRANCH
          git subtree pull --prefix opencv https://github.com/opencv/opencv.git master --squash
          git commit -m "chore: update opencv subtree" || echo "No changes to commit"
          git push https://git:${GH_TOKEN}@github.com/${{ github.repository }}.git $BRANCH

      - name: Workflow Summary
        run: |
          echo "Subtree updated successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Subtree:** ${{ inputs.subtree }}" >> $GITHUB_STEP_SUMMARY
